### ISSUE TITLE
还存在一些小问题

### ISSUE THREAD

**Issue by waltye** [dcb9/phpcron#2]
1. 启动时，会提示`nohup: ignoring input and appending output to ‘nohup.out’`，然后在当前目录生成一个空的nohup.out文件。
2. 每次写日志都写三条，正常不是应该是一条嘛。

**Comment by dcb9** [comment]
1. 启动时提示的那个是 nohup 命令的原因，可以使用：

```
nohup command > /dev/null 2>&1 &
```
1. 把日志的详细内容贴一下，理论上来说执行一条命令会有两条记录，一条记录为开始执行，另一条为执行结束。

**Comment by dcb9** [comment]
![cl f4cftoaf8geyxj8o5 2b](https://cloud.githubusercontent.com/assets/3984347/8797686/ac6e406e-2fcf-11e5-8345-66db60e33c1f.jpg)

由于你只有一个计划任务，所以会这样
- 第一条记录是获取计划任务
- 第二条记录是开始执行数据库那一条任务
- 第三条记录是执行的那条命令是成功了还是失败了，以及相应的输入结果

如果不想每次获取时生成一条记录的话把 [phpcron.php](https://github.com/dcb9/phpcron/blob/master/bin/phpcron.php) 里面的以下内容删除就可以了。

```
$phpcron->on('getNeedsExecTasks', function () use ($phpcron){
    Phpcron\Utils::log(array(
        'cron_name'=>$phpcron->role[ROLE].'获取当前需要执行的计划任务',
        'crontab_id'=>-2,
    ));
});
```
